articulated:
  base_dir: D:/articulated_pc/experiment-002
  debug: false
  imu_friendly_name_mapping:
    A-1: 782184507cf8
    A-2: 30c6f751c998
    A-3: 78218450b200
    A-4: e89f6d75c1e4
    A-5: e89f6d75bbb0
    A-6: e89f6d75f978
    A-7: e89f6d749624
    B-1: e89f6d75b83c
    B-2: e89f6d74a5a0
    B-3: 30c6f751c74c
    B-4: e89f6d75fcc4
  name: experiment-001
  realsense_friendly_name_mapping:
    L-1: f0271808
    L-2: '011422071122'
  realsense_recorder_endpoint: http://localhost:5050
  targets:
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - bottle-014-1
    tag: bottle-014
    uuid: f5511c12-7380-11ed-ac8c-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - bottle-015-1
    - bottle-015-2
    tag: bottle-015
    uuid: f551432d-7380-11ed-a810-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - bottle-017-1
    tag: bottle-017
    uuid: f551432e-7380-11ed-b08b-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - bottle-018-1
    tag: bottle-018
    uuid: f551432f-7380-11ed-ba68-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - bottle-023-1
    tag: bottle-023
    uuid: f5514330-7380-11ed-bb01-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - bottle-028-1
    tag: bottle-028
    uuid: f5514331-7380-11ed-a60f-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - bottle-031-1
    tag: bottle-031
    uuid: f5514332-7380-11ed-94ae-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - box-005-1
    - box-005-2
    - box-005-3
    tag: box-005
    uuid: f5514333-7380-11ed-9a86-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - box-024-1
    - box-024-2
    tag: box-024
    uuid: f5514334-7380-11ed-a94f-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - box-026-1
    tag: box-026
    uuid: f5514335-7380-11ed-9a76-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - box-027-1
    - box-027-2
    - box-027-3
    tag: box-027
    uuid: f5514336-7380-11ed-8f21-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - box-033-1
    tag: box-033
    uuid: f5514337-7380-11ed-b6cc-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - bucket-004-1
    - bucket-004-2
    tag: bucket-004
    uuid: f5514338-7380-11ed-9ff2-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - bucket-019-1
    tag: bucket-019
    uuid: f5514339-7380-11ed-be2c-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - bucket-021-1
    tag: bucket-021
    uuid: f551433a-7380-11ed-a595-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - bucket-022-1
    tag: bucket-022
    uuid: f551433b-7380-11ed-9ef5-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - bucket-057-1
    tag: bucket-057
    uuid: f551433c-7380-11ed-bc2c-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - clip-009-1
    tag: clip-009
    uuid: f551433d-7380-11ed-96ac-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - clip-029-1
    tag: clip-029
    uuid: f551433e-7380-11ed-8d4e-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - clip-032-1
    - clip-032-2
    tag: clip-032
    uuid: f551433f-7380-11ed-a715-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - clip-036-1
    tag: clip-036
    uuid: f5514340-7380-11ed-bcf6-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - clip-042-1
    tag: clip-042
    uuid: f5514341-7380-11ed-a0fe-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - cup-007-1
    tag: cup-007
    uuid: f5514342-7380-11ed-88e8-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - cup-030-1
    - cup-030-2
    tag: cup-030
    uuid: f5514343-7380-11ed-b544-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - cup-044-1
    tag: cup-044
    uuid: f5514344-7380-11ed-8d30-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - cup-045-1
    tag: cup-045
    uuid: f5514345-7380-11ed-9dd7-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - drawer-001-1
    tag: drawer-001
    uuid: f5514346-7380-11ed-998e-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - drawer-003-1
    - drawer-003-2
    tag: drawer-003
    uuid: f5514347-7380-11ed-af57-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - drawer-006-1
    tag: drawer-006
    uuid: f5514348-7380-11ed-9e0f-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - drawer-010-1
    tag: drawer-010
    uuid: f5514349-7380-11ed-80f2-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - drawer-020-1
    tag: drawer-020
    uuid: f551434a-7380-11ed-93c7-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - eyeglasses-039-1
    tag: eyeglasses-039
    uuid: f551434b-7380-11ed-8e40-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - eyeglasses-040-1
    tag: eyeglasses-040
    uuid: f551434c-7380-11ed-8417-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - eyeglasses-049-1
    tag: eyeglasses-049
    uuid: f551434d-7380-11ed-94f8-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - eyeglasses-050-1
    - eyeglasses-050-2
    - eyeglasses-050-3
    tag: eyeglasses-050
    uuid: f551434e-7380-11ed-8796-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - eyeglasses-051-1
    - eyeglasses-051-2
    tag: eyeglasses-051
    uuid: f551434f-7380-11ed-bf2d-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - faucet-038-1
    tag: faucet-038
    uuid: f5514350-7380-11ed-ac03-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - faucet-043-1
    tag: faucet-043
    uuid: f5514351-7380-11ed-a32e-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - faucet-046-1
    tag: faucet-046
    uuid: f5514352-7380-11ed-a949-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - faucet-047-1
    tag: faucet-047
    uuid: f5514353-7380-11ed-b6a5-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - faucet-048-1
    tag: faucet-048
    uuid: f5514354-7380-11ed-ab92-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - misc-011-1
    tag: misc-011
    uuid: f5514355-7380-11ed-8970-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - misc-016-1
    tag: misc-016
    uuid: f5514356-7380-11ed-96c1-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - misc-025-1
    tag: misc-025
    uuid: f5514357-7380-11ed-be4e-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - scissors-037-1
    tag: scissors-037
    uuid: f5514358-7380-11ed-afdd-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - scissors-052-1
    tag: scissors-052
    uuid: f5514359-7380-11ed-b8b6-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - scissors-053-1
    tag: scissors-053
    uuid: f551435a-7380-11ed-8af9-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - scissors-054-1
    tag: scissors-054
    uuid: f551435b-7380-11ed-a34c-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - stapler-013-1
    tag: stapler-013
    uuid: f551435c-7380-11ed-9ebf-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - stapler-034-1
    - stapler-034-2
    tag: stapler-034
    uuid: f551435d-7380-11ed-ba9b-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - stapler-035-1
    tag: stapler-035
    uuid: f551435e-7380-11ed-aa20-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - stapler-055-1
    tag: stapler-055
    uuid: f551435f-7380-11ed-8f97-a8a159b5934c
  - associated_calibration: _cali-0
    finished: true
    imu_dependency: []
    recordings:
    - stapler-056-1
    tag: stapler-056
    uuid: f5514360-7380-11ed-9858-a8a159b5934c
  tcpbroker_endpoint: http://localhost:18889
