export OSS_ENDPOINT="10.52.21.125:10000"
export OSS_SRC_BUCKET="imu-auto-src"
export OSS_DST_BUCKET="imu-auto-dst"
export OSS_ACCESSKEY="RootAccessKey"
export OSS_SECRETKEY="JEYzvyMqr8kM2nMy"
export OSS_BUCKET="imu-auto-src"